### ISSUE TITLE
Problem with SSH 

### ISSUE THREAD

**Issue by mah88** [opendaylight/sfc#2]
If I connected to the VM through SSH and run the tool with "-i eth0","-d forward" and "-v on", I found it Send many packets with no end. That means it send back all SSH TCP packets.

So how to solve the issue ? I used it on Ubuntu VM.

**Comment by tykeal** [comment]
Please either open a bug report at https://bugs.opendaylight.org for which you'll need account. The account can be created at https://identity.opendaylight.org

Or, please ask a question on the sfc-dev mailing list at https://lists.opendaylight.org or at https://ask.opendaylight.org
