### ISSUE TITLE
Problem with running the script

### ISSUE THREAD

**Issue by LeonardLi** [opendaylight/sfc#3]
I run the demo.sh and all goes well until I find the console get stuck in the out loop like: connection to 127.0.0.1 closed. And I check the vagrant status to find that all the VM are not created.
By the way, I mean the scripts in /sfc-demo/sfc103

**Comment by tykeal** [comment]
Please either open a bug report at https://bugs.opendaylight.org for which you'll need account. The account can be created at https://identity.opendaylight.org

Or, please ask a question on the sfc-dev mailing list at https://lists.opendaylight.org
